version: "3.8"

services:
  api:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000" # Prometheus metrics
    environment:
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - WEB3_PROVIDER_URL=${WEB3_PROVIDER_URL}
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  grafana_data:
